### ISSUE TITLE
Args with type of Set get mutated after going through produce.

### ISSUE THREAD

**Issue by justinmwarner** [immerjs/immer#815] opened 2021-06-16 15:21 UTC
## 🐛 Bug Report

When passed a Set as an arg to produce, immer adds some functions to it. These functions then escape the produce function.

## Link to repro

https://codesandbox.io/s/immer-playground-forked-1d3gc?file=/src/index.js

## To Reproduce

Run the repro

## Observed behavior

I wouldn't expect produce to change an arg passed in this way.

## Expected behavior

Produce should only return the new object with updated values where needed. In my example, newX should no thave additional properties/functions on it, it should continue being `[]`. 

## Environment

- **Immer version:** 9.0.3
- [x] I filed this report against the _latest_ version of Immer

_Note: adding mutliple bugs that may be related, feel free to link/close as needed on your end, I just want to keep this clean_

**Comment by mweststrate** [comment] 2021-06-24 08:45
Duplicate of #816

**Closed by mweststrate** 2021-06-24 08:45 UTC
