### ISSUE TITLE
"'getPrototypeOf' on proxy: trap returned neither object nor null" on Chrome 77

### ISSUE THREAD

**Issue by Artoria-0x04** [immerjs/immer#428] opened 2019-09-17 09:45 UTC
## 🐛 Bug Report

`isPlainObject` method throws a "'getPrototypeOf' on proxy: trap returned neither object nor null" on Chrome 77, with my current observation.

I haven't locate the problem precisely, but I'll try to describe the whole progress at my best.

When manipulating a draft, I traced my code into a `isPlainObject` call on a draft, and an error above was thrown on the line:
`var proto = Object.getPrototypeOf(value);`.
![image](https://user-images.githubusercontent.com/1183568/65030481-39c19d80-d972-11e9-9b6b-55d4d28f2932.png)

`value` is a draft and when I digging in, into the getPrototypeOf trap:
`Object.getPrototypeOf(target.base)` correctly evaluates and returns `null` in the devtool. After the trap returns, the error was thrown on the next step.
![image](https://user-images.githubusercontent.com/1183568/65030518-46de8c80-d972-11e9-8f84-a6ae1914d544.png)

What's worth noting is the error raised only on Chrome 77.

## To Reproduce

Still trying to minimize reproduce.

## Expected behavior

As the `getPrototypeOf` trap returns `null`, the "'getPrototypeOf' on proxy: trap returned neither object nor null" error should not be thrown.

## Link to repro (highly encouraged)

Please provide either a [CodeSandbox demo](https://codesandbox.io/s/82zqr6n3kj) or a minimal repository on GitHub.

## Environment

-   **Immer version:** 
4.0.0
-   [ ] Occurs with `setUseProxies(true)`
-   [ ] Occurs with `setUseProxies(false)` (ES5 only)
with default settings

**Comment by mweststrate** [comment] 2019-09-19 15:07
Could you provide a small reproduction, for example in a code sandbox?

**Comment by foisonocean** [comment] 2019-09-20 08:08
Same issue in my project, but I can not reproduce it in the CodeSandbox demo.

**Comment by mweststrate** [comment] 2019-09-20 14:25
So it is not just the browser? Then some deeper diving is needed I fear.
Are there any polyfills active that could hamper the situation, cross
document transportation of the objects, etc etc?

**Comment by alcuadrado** [comment] 2019-09-26 23:36
I got here because I'm having the same issue in node 12.11.0, and I think that you may find this useful.

Here's how to reproduce it.

Open a node v12.11.0 and paste this:

```js
Object.getPrototypeOf(new Proxy(Object.create(null), {
  getPrototypeOf(target) {
    return Reflect.getPrototypeOf(target)
  }
}))
```

I think it's a regression in v8 that shipped in chrome 77 and and node v12.11.0.

**Comment by foisonocean** [comment] 2019-09-27 02:50
@alcuadrado 
But this only happens in Node.js and Chrome. Is this a bug of V8?

**Comment by mweststrate** [comment] 2019-09-27 10:09
Seems like it! Probably best report it there. In my experience they are
quite receptive for this kind of pin-point accurate bugs and fix it quickly

Op vr 27 sep. 2019 03:50 schreef Zhao <notifications@github.com>:

**Comment by alcuadrado** [comment] 2019-09-27 15:00
> But this only happens in Node.js and Chrome. Is this a bug of V8?

Yes, it's a bug in v8.

> Probably best report it there

I did: https://bugs.chromium.org/p/v8/issues/detail?id=9781

**Comment by mweststrate** [comment] 2019-09-27 15:05
Awesome, thanks!

**Comment by mweststrate** [comment] 2019-09-28 19:07
Closing now, as this is beyond Immer. Let's hope they ship soon, but at least the fix landed quickly :)

**Closed by mweststrate** 2019-09-28 19:07 UTC
