### ISSUE TITLE
"undefined is not a function" (Win/Chrome)

### ISSUE THREAD

**Issue by njradford** [immerjs/immer#585] opened 2020-04-23 23:39 UTC
I'm seeing many errors from users who are using Windows 10 and Chrome 80.39

```
File webpack:///./node_modules/@reduxjs/toolkit/node_modules/immer/dist/immer.module.js line 97 col 20 in each
ownKeys(value).forEach(function (key) {
File webpack:///./node_modules/@reduxjs/toolkit/node_modules/immer/dist/immer.module.js line 562 col 1 in [anonymous]
each(objectTraps, function (key, fn) {
Hide 1 non-project frame
Object.<anonymous>
File webpack:///webpack/bootstrap line 19 col 22 in __webpack_require__
modules[moduleId].call(module.exports, module, module.exports, __webpack_require__);
Show 1 non-project frame
File webpack:///webpack/bootstrap line 19 col 22 in __webpack_require__
modules[moduleId].call(module.exports, module, module.exports, __webpack_require__);
File webpack:///webpack/bootstrap line 83 col 10 in [anonymous]
return __webpack_require__(__webpack_require__.s = 856);
Show 1 non-project frame
```

If this is a babel polyfill issue, feel free to suggest where else I should take this issue.

**Comment by mweststrate** [comment] 2020-05-22 18:32
Duplicate of #425. If you have a consistent production please provide it in that thread. Closing this one for now. 

Note that without a reproduction this issue won't be fixed. But yes, it feels as a polyfill issue or something.

**Closed by mweststrate** 2020-05-22 18:32 UTC

**Comment by markatlish** [comment] 2021-01-04 21:10
Also seeing this on Chrome / Windows, against immer 8.0.0.  ownKeys appears to be undefined on line 83.
```
File ../../src/utils/common.ts line 83 col 50 in each
;(enumerableOnly ? Object.keys : ownKeys)(obj).forEach(key => {
File ../../src/core/proxy.ts line 208 col 1 in [anonymous]
each(objectTraps, (key, fn) => {
```

![image](https://user-images.githubusercontent.com/66799581/103579507-43d01e00-4e8d-11eb-8c56-2a7777cad174.png)

We're using only `import 'react-app-polyfill/stable';` with below browserlist setup on react-scripts 4.0.1, @babel/core@7.12.3, babel-loader@8.1.0:
```
"browserslist": {
    "production": [
      ">0.2%",
      "not dead",
      "not op_mini all"
    ],
    ...
```

Observed on Chrome/53.0.2785.143 Win 10;  also Chrome/84.0.4147.135

Reporting here since #425 is locked

**Comment by mweststrate** [comment] 2021-01-04 21:55
@markatlish please do open a fresh issue with the requested info, rather than reporting on old closed ones, thanks!
