### ISSUE TITLE
IE11 "Unable to get property 'value' of undefined or null reference"

### ISSUE THREAD

**Issue by graue** [immerjs/immer#362] opened 2019-05-11 00:55 UTC
## 🐛 Bug Report

We're seeing a bunch of breakage in production for IE11 users on this line in `shallowCopy`:

https://github.com/immerjs/immer/blob/master/src/common.js#L62

```.js
ownKeys(base).forEach(key => {
    if (key === DRAFT_STATE) {
        return // Never copy over draft state.
    }
    const desc = Object.getOwnPropertyDescriptor(base, key)
    let {value} = desc       // <- BREAKS: Unable to get property 'value' of undefined or null reference
```

On the micro level, one of the keys that gets returned from `Object.getOwnPropertyNames` (I don't know which one) appears to return undefined when calling `Object.getOwnPropertyDescriptor` with it, immediately after.

On the macro level, this is happening the moment we try to access an Immer draft, which is a plain object, like this:

```.js
  return produce(state, draft => {
    // ...
    const draftUserInfo = draft.userInfo   // this line blows up
```

Unfortunately, I can't get a repro, so this is more a call for help than a bug report. Any idea why this might be happening? Could Immer potentially be more defensive here, skipping over keys that don't have a property descriptor?

## Environment

-   **Immer version:**
-   [ ] Occurs with `setUseProxies(true)`
-   [x] Occurs with `setUseProxies(false)` (ES5 only)

**Comment by aleclarson** [comment] 2019-05-11 01:06
Duplicate of #336

**Closed by aleclarson** 2019-05-11 01:06 UTC
Labels: bug

**Comment by aleclarson** [comment] 2019-05-11 01:07
In particular, see this comment: https://github.com/immerjs/immer/issues/336#issuecomment-473884546

**Comment by graue** [comment] 2019-05-11 01:25
Thanks so much for the pointer, @aleclarson. How about implementing the proposed workaround in #336 into Immer? It seems unlikely to hurt performance, and could benefit a lot of people who are going to run into this problem when they adopt Immer.

**Comment by aleclarson** [comment] 2019-05-11 01:29
Someone could send a PR or open an issue for babel-preset-env to see if this bug could be polyfilled for those environments. Always be sure to test IE11 before shipping if your product wants to support it.

**Comment by graue** [comment] 2019-05-11 01:35
So you have a philosophical objection to fixing it?

I guess I'm a little confused because @mweststrate wrote:

>if:
>
>* A work around is small (code wise)
>* Doesn't impact performance for non affected environments
>* Behaves semantically entirely the same as non affected environments (replacing exceptions with non-throwing deviating behavior is worse, not better)
>
>Then we can be pragmatic and include a work around, clearly commented.

which seems clearly the case.

**Comment by aleclarson** [comment] 2019-05-11 12:12
> So you have a philosophical objection to fixing it?

No, but if IE11 is affected, `babel-preset-env` seems like a better place to fix it.

**Comment by mweststrate** [comment] 2019-05-13 07:50
Note that the work around is also technically incorrect, as in, it makes
assumptions which might be false.

**Comment by graue** [comment] 2019-05-14 00:25
Turns out that workaround doesn't fix IE11. I'm unable to reproduce the issue, even in a Win7/IE11 session on Browserstack, but the website I work on is seeing hundreds of IE11 users affected by this issue in Immer.

For whatever reason, Immer's assumption that if it obtains an object key from `getOwnPropertyNames` or `getOwnPropertySymbols`, it can then retrieve a non-null descriptor for that key, isn't true in practice in _some_ situation affecting IE11 users.

One workaround might be to make Immer more robust to this situation, by, say, skipping over properties that do not have a property descriptor when making a shallow copy. It would make the issue less fatal to us. But I understand you may not want to do that because it would be arguably incorrect behavior.

Continuing to debug this would exceed the time and effort that Immer is saving us to begin with, so regrettably, we're going to stop using Immer. I'm sorry I was unable to help track this down and resolve the root issue.

**Comment by aleclarson** [comment] 2019-05-14 00:27
@graue You could always maintain a fork. :)

@mweststrate WDYT? Should we check for an undefined descriptor just to be safe?

**Comment by mweststrate** [comment] 2019-05-14 05:41
What does skipping mean? That the entire property is suddenly gone in the
copy? I gladly see a small reproduction first to discover what this means
or in what circumstances this happens.

Op di 14 mei 2019 02:27 schreef Alec Larson <notifications@github.com>:

**Comment by mweststrate** [comment] 2019-05-14 07:36
@graue would you mind opening a fresh issue with reproduction, rather than replying to an old closed one The reason is that this is quite an generic error, that can be caused by Immer, but also by your own code (since the work around doesn't work for example), the HTML document mode (from what I've seen when googling for the error) etc. 

So without small reproduction project in which we can analyze both the cause and the impact of an solution, we can't mean much for you. Probably you might need to find out what specific IE 11 version your users are using that are affected by this

**Comment by graue** [comment] 2019-05-14 19:08
@mweststrate, as I said, I'm going off widespread error logs in production (we use https://sentry.io/) and unfortunately cannot reproduce the issue myself. Not in Browserstack nor on my colleague's Windows machine that is running IE11 natively.

If I learn more I will certainly share, though.

**Comment by linehammer** [comment] 2021-09-13 05:21
The issue arise when js/jquery is not able to refer to the element. It is because at the time of rendering the page(view),  object is null or undefined - which means that there is no instance of a class in the variable. If you are getting data for object from an async call(api's), these kind of problems will arise. So you should always check the object whether it is null or undefined then if it is not, you can access its properties.

The standard way to catch null and undefined simultaneously is this:

if (variable == null) {
     // your code here.
}

Because null == undefined is true, the above code will catch both null and undefined.

Also you can write equivalent to more explicit but less concise:

```
if (variable === undefined  variable === null) {
     // your code here.
}
```

This should work for any variable that is either undeclared or declared and explicitly set to null or undefined.

In most cases it is related to getElementById(). So getting a value from an input could look like this:

var value = document.getElementById("frm_new_user_request").value

Also you can use some JavaScript framework, e.g. jQuery, which simplifies operations with DOM (Document Object Model) and also hides differences between various browsers from you.

Getting a value from an input using [jQuery](http://net-informations.com/jq/iq/default.htm) would look like this:

```
input with ID "element": var value = $("#element).value
input with class "element": var value = $(".element).value
```
