### ISSUE TITLE
Should a normal assignment throw an error if object is frozen?

### ISSUE THREAD

**Issue by maximedupre** [immerjs/immer#469] opened 2019-11-26 18:46 UTC
## 🚀 Feature Proposal

    const project = produce({
	    id: 1,
	    tracks: [{ id: 1 }]
    }, () => {});

    project.id = 2 // Does not throw error
    Object.assign(project, {id: 2}) // Uncaught TypeError: Cannot assign to read only property 'id' of object '#<Object>'

Shouldn't it throw an error in both cases? 

## Motivation

The current way is error prone. There is probably a technological/architectural reason why it is currently implemented that way though...

**Comment by maximedupre** [comment] 2019-11-26 19:04
Ah, for `project.id = 2` to throw an error, the execution needs to be in strict mode. That's a JS thing though, nothing to do with immer. Weird.

**Comment by mweststrate** [comment] 2019-11-27 22:50
It should throw in either case. Could you provide a reproduction in code sandbox or as PR?

**Comment by maximedupre** [comment] 2019-11-29 19:07
Here is a reproduction:

https://codepen.io/maximedupre/pen/xxxoxMK

Open the console and you should see an error. Comment `use strict` and the error will disappear on next code refresh

**Comment by mweststrate** [comment] 2020-01-09 19:25
I get an error still when using use strict. 
<img width="1655" alt="Screen Shot 2020-01-09 at 19 23 30" src="https://user-images.githubusercontent.com/1820292/72098033-9a0b8f00-3315-11ea-858e-907070b6015e.png">

Closing for now as the error or the issues we are talking about isn't immediately clear. If this issue is to be chased further, please open a PR with a unit test capturing exactly the offending behavior, as it still isn't clear to me from the comments or issue what and what isn't expected to work.

**Closed by mweststrate** 2020-01-09 19:25 UTC
Labels: cannot reproduce

**Comment by adelespinasse** [comment] 2022-04-21 15:20
Note: The issue is that there is no exception thrown when NOT in strict mode. This is still the case. It looks like @mweststrate had it backwards.

Of course, hopefully everyone is using strict mode whenever possible by now, but there are probably cases where it's not used, and people will be confused by the lack of exceptions.
